name: p38_delta_loss
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.3.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - comm=0.1.2
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - ffmpeg=4.2.2
  - freetype=2.12.1
  - frozenlist=1.2.0
  - future=0.18.2
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1s
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.28.1
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tensorboard-data-server=0.6.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.12
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!157.20191217
  - xz=5.2.10
  - yarl=1.8.1
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - antlr4-python3-runtime==4.8
    - asttokens==2.0.8
    - cachetools==4.2.4
    - chess==1.6.1
    - colorama==0.4.5
    - comet-ml==3.13.2
    - configobj==5.0.6
    - cssselect2==0.7.0
    - cycler==0.11.0
    - dulwich==0.20.46
    - easy-to-hard-data==1.0.0
    - einops==0.3.2
    - everett==3.0.0
    - executing==1.1.1
    - fonttools==4.37.4
    - fsspec==2023.6.0
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.50.0
    - huggingface-hub==0.16.4
    - hydra-core==1.1.1
    - icecream==2.1.3
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - jsonschema==4.16.0
    - kiwisolver==1.4.4
    - line-profiler==4.0.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - numpy==1.21.6
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.2.2
    - omegaconf==2.1.2
    - packaging==21.3
    - pandas==1.3.5
    - pillow==8.2.0
    - pkgutil-resolve-name==1.3.10
    - protobuf==3.20.3
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pyyaml==6.0
    - reportlab==3.5.68
    - requests-oauthlib==1.3.1
    - requests-toolbelt==0.10.0
    - rsa==4.9
    - scipy==1.7.0
    - seaborn==0.11.2
    - semantic-version==2.10.0
    - setuptools==59.5.0
    - svglib==1.1.0
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.8.0
    - tinycss2==1.2.1
    - torch-tb-profiler==0.4.0
    - tqdm==4.62.3
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - wurlitzer==3.0.2
    - zipp==3.9.0
