alpha: 0
clip: null
epochs: 130
lr: 0.001
lr_decay: step
lr_factor: 0.1
lr_schedule:
  - 100
  - 115
lr_throttle: true
optimizer: adam
save_period: 1
test_batch_size: 250
test_mode: default
train_batch_size: 250
train_mode: delta
val_period: 1
warmup_period: 10
weight_decay: 0