alpha: 0.01
clip: 10
epochs: 50
lr: 0.001
lr_decay: step
lr_factor: 0.1
lr_schedule:
  - 100
lr_throttle: True
optimizer: adam
save_period: 1
test_batch_size: 16
test_mode: default
train_batch_size: 100
train_mode: delta
val_period: 1
warmup_period: 10
weight_decay: 0